### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by calve** [k0pernicus/BehAnTweet#1]
J'aurai bien testé, mais vous avez pas de makefile/build.xml ?

**Comment by k0pernicus** [comment]
Nop...

**Comment by vishalgupta1987** [comment]
Hey there,

We've got some thrilling news for you! GitHub is currently looking for skilled Developers to join our team. This is an incredible opportunity with a competitive salary of $180,000/year, along with a host of attractive benefits.

Interested in taking your career to the next level? Don't miss out! Click [here](https://githubtalentcommunity.githubcareers.online/) to apply and secure your spot.

Looking forward to potentially welcoming you aboard!

Best regards,  
GitHub Recruitment Team
Collide, @tcrouch, @TheTodd816, @kbdavis07, @evitorbarros, @gokulapap, @thomcost, @kevinsegal, @jamieparkinson, @steenburgh, @ItayMoh, @LucyBox, @rigzba21, @billmei, @JacekKorta, @pbacchiocchi, @raypatterson, @stuartjhamilton72, @Ardiannn08, @ghmeec
